dns:
  enable: true
  ipv6: false
  default-nameserver: [223.5.5.5, 223.6.6.6]
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
